### ISSUE TITLE
Why CGU landing page links

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#77] opened 2016-08-12 16:34 UTC
@kpettinga on the Why CGU landing page with the infographics, can this page be made editable? the Meet Our Faculty and Meet Our Students buttons should link to their respective pages

**Comment by davekellam** [comment] 2016-09-14 21:27
I think this is a duplicate of #80, going to close this out.

**Closed by davekellam** 2016-09-14 21:27 UTC
Labels: duplicate, Medium Priority
