### ISSUE TITLE
Programs: courses padding/width issue in Safari

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#49] opened 2016-07-15 21:14 UTC
On the program pages, in Safari, the Courses layout gets messed up

![screen shot 2016-07-15 at 12 37 12 pm](https://cloud.githubusercontent.com/assets/1680051/16888687/a2deab8c-4aaf-11e6-8152-62574c150b2e.png)

**Comment by davekellam** [comment] 2016-07-26 19:20
Here's an example: http://cgu.wpengine.com/academics/program/phd-media-studies/

Seems like the width percentages are just a little bit off. SASS seems to generate a width of 31.76% for the blocks, which is fine for Chrome, but seems to need 31.73% or less for Safari. Going to throw this back to Kirk, as it's more of a front-end thing that could affect the site's overall grid.

**Comment by davekellam** [comment] 2016-09-14 21:50
Seems to be a duplicate of #34. Going to close this out.

**Closed by davekellam** 2016-09-14 21:50 UTC
Labels: bug
