### ISSUE TITLE
Child page navigation to Resources & Support

### ISSUE THREAD

**Issue by Jessdwilson** [ObjectiveSubject/cgu#96] opened 2016-09-09 22:04 UTC
From Andrea:

Who adds the child page navigation to Resources & Support:http://cgu.wpengine.com/academics/resources-support/? 

This is something we need to address. We have a [child_pages] shortcode which will automatically grab all child pages of the current page and create a tabbed nav with all of them listed. This is a problem, however, when a page has too many child pages. The tabbed nav design does not accommodate a large number of items. We anticipated this happening in the early stages of the design, and think we need to consider a sidebar approach similar to the admissions pages.

**Comment by kpettinga** [comment] 2016-09-12 08:27
Closing this because it's a duplicate of https://github.com/ObjectiveSubject/cgu/issues/89

**Closed by kpettinga** 2016-09-12 08:27 UTC
Labels: Critical, From Client
